--- 
abstract: A storage class for Catalyst Authentication using DBIx::Class
author: Jason Kuri (jayk@cpan.org)
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Authentication-Store-DBIx-Class
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Plugin::Authentication: 0
  Catalyst::Runtime: 0
  Test::More: 0
version: 0.10
